# Generated by Django 5.1.2 on 2024-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160, verbose_name='nombre')),
                ('description', models.TextField(max_length=500, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('available', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen')),
            ],
        ),
    ]
